import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider, Stack } from "@chakra-ui/react";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Stack maxW={"1340px"} mx="auto">
          <ChakraProvider>
            <Navbar />
            {children}
          </ChakraProvider>
        </Stack>
      </body>
    </html>
  );
}
